apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-domain
  labels:
    app: clinic-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-domain
  template:
    metadata:
      labels:
        app: clinic-domain
    spec:
      containers:
      - name: clinic-domain
        image: cs548/clinic-domain
        env:
        - name: DATABASE_USERNAME
          value: cs548user
        - name: DATABASE_PASSWORD
          value: dbuserpw
        - name: DATABASE
          value: cs548
        - name: DATABASE_HOST
          value: cs548db
        - name: MEMORY_THRESHOLD
          value: "10485760"
        imagePullPolicy: Never
