apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs548db
  labels:
    app: cs548db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs548db
  template:
    metadata:
      labels:
        app: cs548db
    spec:
      containers:
      - name: cs548db
        image: cs548/clinic-database
        env:
        - name: POSTGRES_PASSWORD
          value: dbuserpw
        - name: DATABASE_PASSWORD
          value: dbuserpw
        imagePullPolicy: Never
